apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apiservers.config.openshift.io
spec:
  group: config.openshift.io
  scope: Cluster
  names:
    kind: APIServer
    singular: apiserver
    plural: apiservers
    listKind: APIServerList
  versions:
  - name: v1
    served: true
    storage: true
